package org.latlab.learner.geast.operators;

import org.latlab.learner.geast.IModelWithScore;

/**
 * A candidate given initially that is not generated by any search operator.
 * 
 * @author leonard
 * 
 */
public class GivenCandidate extends SearchCandidate {

    private final static String ELEMENT = "given";

    public GivenCandidate(IModelWithScore given) {
        super(given, given.model(), given);
    }

    @Override
    public boolean isNew() {
        return false;
    }

    @Override
    public String attributes() {
        return "";
    }

    @Override
    public String element() {
        return ELEMENT;
    }

    @Override
    public String name() {
        return getClass().getSimpleName();
    }

	@Override
	public String operatorName() {
		return ELEMENT;
	}

}
